### ISSUE TITLE
Data Processing: processing GPS data into format required for estimation/calibration

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#13]
Add to initial scripts written to process the GPS data provided by CMAP into various estimation datasets and calibration targets. Initial need is to support modification and then calibration of the stop generation models transferred from Detroit.

Review script is ./dev/data_gps.R

**Comment by ColSmith76** [comment]
@RickyZapata:
Notes for the stop generation model calibration data:
1. Identify most likely home location for the truck (where most of its tour starts occur)
2. Tag the subzones for trip origins and destinations with subzone centroid locations
3. Calculate home location to trip destination distances (great circle distance)
4. Develop distributions of home location to trip destination distances (excluding the return to home location trips, we don;t want to include the home location to home location distance which would skew the distribution)
5. Check if distributions vary by the characteristics we have in the data, e.g. vehicle type, county of home location (are distributions longer for trucks in the outer counties compared to say Cook county)
6. Also look at this at the truck level -- are there some trucks making mostly/all close by stops, and some making stops at much further away locations?

**Comment by ColSmith76** [comment]
Additional GPS data characteristics:
Tour types: for estimation and calibration of the tour types model:
- single stop or multistop? Single stop has one stop away from the tour start/end location. Multi stop has > 1
- tour start and end same or different location (are there are like this given the way the GPS data has been processed?)
- tour start and end at truck base location or different location? Given we've defined truck base as main start/end location, are there some tours that start and end in different places for that truck?
- tour type variable is the combination of single/multiple, base or not base and start end end, and same or different location, coded as there character code, e.g. BBS would be base to base, single stop, NNM would be not base to not base, multi-stop.

**Comment by ColSmith76** [comment]
Tour duration, lengths and other characteristics:
for each tour:
1. Number of stops (not including the return to start stop)
2. Total time
3. Total travel time
4. Total stop duration
5. Total distance traveled (based on network skim distances)
6. Whether all stops were within the region or included some external stops
7. Maximum straightline distance from the tour start location
8. Optimal routing of the tour: given the stop locations in the tour, what is the minimum distance according to the traveling salesman algorithm (can compare to the actual distance to see how optimal the routing is, e.g, ratio of actual tour distance to optimal distance)

**Comment by ColSmith76** [comment]
Stop duration data: for estimating/calibrating the stop duration model:
stop durations for each stop.. Distributions by vehicle type, any other characteristics that we can observe in the GPS data

**Comment by ColSmith76** [comment]
Arrival time at the first stop: for estimating/calibrating the arrival time model:
Arrival time at the first stop on the tour.

**Comment by ColSmith76** [comment]
@RickyZapata please can you add a comment here on what's left to do at this point (e.g., calculating distributions by distance based on the skim network distance as opposed to subzone to subzone GCD)

**Comment by RickyZapata** [comment]
Left to do:
1. Total Tour Distance (via skims)
2. Optimal Routing/Traveling Salesman algorithm

**Comment by ColSmith76** [comment]
Need skims to complete this

**Comment by ColSmith76** [comment]
@RickyZapata please can you update this issue with the later progress

**Comment by ColSmith76** [comment]
@RickyZapata let's go through this now and see what's left to do/add any new items

**Comment by RickyZapata** [comment]
> Additional summaries:
> 
> 1. Total Tour Distance (via skims) (already have the time distribution)
> 2. Trip distance distribution (1 mile bins)
> 3. Number of stops per tour
> 4. Single stop clusters vs multi stop clusters
> 5. Average stop to stop distance in the clusters (and distribution of stop to stop distances)
> 6. Optimal Routing/Traveling Salesman algorithm (compare actual tour routing in GPS vs travel salesman routing)



Items 1-5 of the above are complete and have been saved in "dev/Data_Processed/CVGPS/Calibration Targets/"

Item 6 (Actual vs. Travelling Salesman comparison in CVGPS) remains but mostly complete
-Ricky

**Comment by ColSmith76** [comment]
Scripts all up to date in the repo
