### ISSUE TITLE
CSVM Tour models: testing 

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#25]
Testing checks of this step are to ensure that the simulated set of tours is reasonably consistent with the observed data in terms of length of tours (number of stops, duration). More detailed calibration will be required beyond these initial checks (e.g., calibrating by tour type (single stop, multi stop) and relationship between optimal routing and actual routing.

**Comment by RickyZapata** [comment]
Update Employment Categories in cv_sim_tours (line 132 &  line 193)

**Comment by ColSmith76** [comment]
Tour model working in application with new specification

**Comment by ColSmith76** [comment]
Closing as testing suggests working correctly with base year inputs
