### ISSUE TITLE
Trip Tables: naming of matrices

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#32]
The output tables are currently named:

$Matrices
                 name dclass         dim   type navalue               description
1   Daily Heavy Truck  FLOAT 3649 x 3649 matrix      -1  base all Heavy CV matrix
2   Daily Light Truck  FLOAT 3649 x 3649 matrix      -1  base all Light CV matrix
3  Daily Medium Truck  FLOAT 3649 x 3649 matrix      -1 base all Medium CV matrix
4      P1 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P1 Heavy CV matrix
5      P1 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P1 Light CV matrix
6     P1 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P1 Medium CV matrix
7      P2 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P2 Heavy CV matrix
8      P2 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P2 Light CV matrix
9     P2 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P2 Medium CV matrix
10     P3 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P3 Heavy CV matrix
11     P3 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P3 Light CV matrix
12    P3 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P3 Medium CV matrix
13     P4 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P4 Heavy CV matrix
14     P4 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P4 Light CV matrix
15    P4 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P4 Medium CV matrix
16     P5 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P5 Heavy CV matrix
17     P5 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P5 Light CV matrix
18    P5 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P5 Medium CV matrix
19     P6 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P6 Heavy CV matrix
20     P6 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P6 Light CV matrix
21    P6 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P6 Medium CV matrix
22     P7 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P7 Heavy CV matrix
23     P7 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P7 Light CV matrix
24    P7 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P7 Medium CV matrix
25     P8 Heavy Truck  FLOAT 3649 x 3649 matrix      -1   base P8 Heavy CV matrix
26     P8 Light Truck  FLOAT 3649 x 3649 matrix      -1   base P8 Light CV matrix
27    P8 Medium Truck  FLOAT 3649 x 3649 matrix      -1  base P8 Medium CV matrix

**Comment by ColSmith76** [comment]
Would you like the names of the matrics to be modified, include a number e.g., mfxx, be formatted in a certain way (e.g., all lower case, no spaces, underscores, etc.)

**Comment by nrferguson** [comment]
My understanding is that, when importing an OMX file to Emme, the mapping of matrix names in the OMX to pre-existing Emme matrices is one of the import tool parameters. Therefore, matrix IDs, matrix names, and matrix descriptions used by Emme are defined within Emme. Only the data in the matrices carry over from the OMX. I think we can use the simplified names below and keep the detail in the descriptions.

htruck_daily
ltruck_daily
mtruck_daily
htruck_p1
ltruck_p1
mtruck_p1
htruck_p2
ltruck_p2
mtruck_p2
htruck_p3
ltruck_p3
mtruck_p3
htruck_p4
ltruck_p4
mtruck_p4
htruck_p5
ltruck_p5
mtruck_p5
htruck_p6
ltruck_p6
mtruck_p6
htruck_p7
ltruck_p7
mtruck_p7
htruck_p8
ltruck_p8
mtruck_p8

**Comment by ColSmith76** [comment]
@nrferguson thanks, that all makes sense and yes we'll use that naming convention

@RickyZapata the code to update is in the tt_build script.. You will see at lines 18-29 how the matrix names etc are built. You can modify that code to build the names Nick has specified, but be careful that the vehicletype and tod fields in the outputMatrices data table still need to use the c("Light", "Medium", "Heavy") for vehicle type and the tod names in upper case to match with what is in the database.

**Comment by ColSmith76** [comment]
Naming convention implemented in the tt_build function
