### ISSUE TITLE
Forecast year inputs: employment control

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#34]
For the forecast year require an employment control file for the CMAP 21 county reqion at TAZ level, with control totals by employment type:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/colins/AppData/Local/Temp/3/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/colins/AppData/Local/Temp/3/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Zone17 | Mesozone | CountyFIPS | NAICS | Employment
-- | -- | -- | -- | --
1 | 17 | 17031 | 11 | 0
2 | 17 | 17031 | 11 | 0
3 | 17 | 17031 | 11 | 0
4 | 17 | 17031 | 11 | 0
5 | 17 | 17031 | 11 | 14

</body>

</html>

**Comment by ColSmith76** [comment]
@nrferguson the ATTR_IN file has total employment and retail employment by subzone. Will you be able to provide future employment by NAICS 2 digit category by TAZ or should we develop a method to grow the base year employment to future total employment (and retail employment) controls, by for example maintaining the share in the TAZ by NAICS 2 from the base year but growing the numbers to match the total?

**Comment by tinleycraig** [comment]
@ColSmith76 @nrferguson Yes we can provide NAICS 2 digit employment. Nick - look in the subzonetm & xsubzonetm files in tg\UrbanSim_inputs (num_jobs_sector_xx fields).

**Comment by nrferguson** [comment]
The MAZ jobs by 2-digit NAICS are in [xsubzonetm_211_2050.csv](https://cmapil.sharepoint.com/:f:/r/sites/csvm-survey-fy21/Shared%20Documents/2%20Data%20Review/[2050_forecast](https://cmapil.sharepoint.com/:f:/r/sites/csvm-survey-fy21/Shared%20Documents/2%20Data%20Review/2050_forecast?csf=1&web=1&e=glGtNw)?csf=1&web=1&e=glGtNw).

**Comment by ColSmith76** [comment]
Received both files and processing is being done, see #42
