### ISSUE TITLE
Future Scenario: Employment Control Data

### ISSUE THREAD

**Issue by RickyZapata** [CMAP-REPOS/cmap_csvm#49]
r211_parcelSum_empsBySZ_2050.csv is missing subzones (and subsequently TAZs) that were present in the base year employment control data. 

Some context on this would be great.

Thank you!

**Comment by nrferguson** [comment]
Apparently that file covered only the 7-county area, not the entire modeling area, and did not include subzones without employment. Please use [r211_empsbySZ_fullmodelingregion_2050.csv](https://cmapil.sharepoint.com/:f:/r/sites/csvm-survey-fy21/Shared%20Documents/2%20Data%20Review/2050_forecast?csf=1&web=1&e=snaqiH). Sorry for the confusion.

**Comment by RickyZapata** [comment]
Nick, thank you for the new file! 

Issue resolved:
Internal and external future scenario employment files have been processed. New future scenario employment file with 3632 TAZs has been processed and written into 'scenarios/future/inputs/'.
