### ISSUE TITLE
Future Year Employment File

### ISSUE THREAD

**Issue by RickyZapata** [CMAP-REPOS/cmap_csvm#52]
Thank you for the most recent future scenario employment file. 

One more question we have is whether you have a similar file with a more detailed breakdown of NAICS2 employment categories. 
Ex., The current file has a NAICS2 31 employment field; does this NAICS2 31 employment field encompass NAICS2 31-33? It would be nice to have separate NAICS2 31, 32, and 33 fields to be consistent with base year file if possible. 

Thank you,
Ricky

**Comment by ColSmith76** [comment]
@nrferguson thanks, we'll make some adjustments to handle that appropriately (the main issue being that when base year firms are grown to the targets, what was happening was that all firms in 32, 33, 45, and 49 were being removed as there was no future employment in those groups and then just the firms that were there in 31,44, and 48 groups were grown to match the totals. Allowing for the more aggregate categories will prevent that happening.

**Comment by ColSmith76** [comment]
@nrferguson Just to confirm then. Base year we have 3.9 million households and 4.9 million jobs. Future year we have 5.0 million households and 5.2 million jobs, for growth of 28% in households and only 8% in employment. Even with some reduction in household size, population growth is outpacing employment growth. Are either the base or the future employment numbers incorrect?

**Comment by ColSmith76** [comment]
Closing this as we have included the flexibility to change to slightly more aggregated employment group controls for the future year and handle the transition from base to future year categories correctly when growing the firm synthesis. Moving the question above about regional control totals to #43
