### ISSUE TITLE
Dashboard: change requests from CMAP

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#53]
Updates to dashboard requested by CMAP:

Dashboard summaries 

1. Equity 

- [ ] Trip generation – starting and ending land uses 

- [ ] Tabulate by EJ areas – CMAP can provide geography 

Energy 

- [x] Tabulations that related to energy/electrification e.g., distribution of distance per day,  density of truck trip ends by time of day, etc.

Adjustments 

- [x] Split Cook into Chicago and suburban Cook – CMAP can provide zone definitions 

- [x] Simplify charts with columns for trip ends outside the modeling area 

- [x] Scenario comparison dashboard – This is done already (see future year dashboard that compares with base, however definitions of scenarios to compare are flexible so dashboard will compare the curent scenario that has just been run with any other reference scenario that has already been run

**Comment by ColSmith76** [comment]
@nrferguson we already have the "chicago" field in the zone layer to identify the TAZs are in the City of Chicago and can therefore split Cook County. So, we just need EJ areas definitions

**Comment by nrferguson** [comment]
[exc_pop_shr_mo50.txt](https://cmapil.sharepoint.com/:t:/r/sites/csvm-survey-fy21/Shared%20Documents/2%20Data%20Review/exc_pop_shr_mo50.txt?csf=1&web=1&e=g6bnXe) is an Emme origin matrix that contains the proportion of population in Economically Disconnected Areas (EDAs) for each TAZ.

**Comment by ColSmith76** [comment]
thanks @nrferguson we'll incorporate this into the model dashboard so that summaries can include it

**Comment by ColSmith76** [comment]
@nrferguson one question on the zone groupings we've derived from the zone layer: the cmap field includes two TAZs that are the only ones in their respective counties. Should these TAZs be included as part of the CMAP region?

TAZ cbd chicago cmap CountyFIPS county state township     sqmi Mesozone county_state
2949   0       0    1      17063 GRUNDY    IL     3408 35.65082      119   GRUNDY, IL
2977   0       0    1      17037 DEKALB    IL     3705 34.65068      121   DEKALB, IL

**Comment by nrferguson** [comment]
Yes. There is one township in Grundy and two townships in DeKalb that are outside the seven counties, but they are included in our MPO planning area.

Nick

**Comment by ColSmith76** [comment]
Geography used in the dashboard is updated to an 11 district system: Chicago, rest of Cook, 8 county zones for the rest of CMAP (including the CMAP parts of Dekalb and Grundy), then a final district for the rest of the model region

**Comment by ColSmith76** [comment]
Most corrections to dashboard done, need new summaries for equity and for electrification

**Comment by ColSmith76** [comment]
Need some guidance on analysis required for equity analysis

**Comment by ColSmith76** [comment]
@nrferguson noticed that the base to stop summaries under cvtm - stop comparison were missing from the version of the dashboard created to compare scenarios (they are in the base compared to validation data version). Need to add the three summaries -- table of mean distance by activity and then goods stops by industry and service stops by industry
