### ISSUE TITLE
Base Year Employment

### ISSUE THREAD

**Issue by RickyZapata** [CMAP-REPOS/cmap_csvm#54]
Hi Nick,

Thank you for the updated HH and ATTR file. If  base year employment numbers have changed, we would also like to request an updated base year employment file broken down by employment category, similar to the file you most recently updated for the future year scenario.

Thank you,
Ricky

**Comment by nrferguson** [comment]
See subzonetm_211_2019.csv and xsubzonetm_211_2019.csv in [2019_base](https://cmapil.sharepoint.com/:f:/r/sites/csvm-survey-fy21/Shared%20Documents/2%20Data%20Review/2019_base?csf=1&web=1&e=bX5FIn).

**Comment by ColSmith76** [comment]
closing, all se data up to date now
