### ISSUE TITLE
Scenario adjustments

### ISSUE THREAD

**Issue by nrferguson** [CMAP-REPOS/cmap_csvm#63]
How do we adjust scenarios for shorter deliveries and cost changes? Highlighted items 6 and 7 in [SensitivityTestDashboardIdeas.docx](https://cmapil.sharepoint.com/:w:/r/sites/csvm-survey-fy21/Shared%20Documents/5%20Model/Model%20Outputs/SensitivityTestDashboardIdeas.docx?d=w892618d58568421db7725f2446e2b56e&csf=1&web=1&e=WGrvFO) don't seem to be included in scenario_adjustments.R.

**Comment by ColSmith76** [comment]
@nrferguson yes, need to do add some extra factors tot he scenario adjustments file to support those scenarios. Will look at that today and make some additions to the file and relevant hooks in the model code. 

For shorter deliveries: influence the shed of stops generated for goods delivery to focus on locations closer to the businesses. This captures locatized delivery. Requires exposing an extra parameter in the stop generation model (in addition to the constant).

For cost changes (e.g. gas tax increases) need to provide an adjustment factor to modify distance sensitivity (i.e., to capture more/less expensive fuel or other distance based operating expenses. 

For benachmarking: studies on metropolitan commercial vehicle VMT sensitivity to operating cost changes. What is a reasonable elasticity?

**Comment by ColSmith76** [comment]
Added and will be in the updated releases
