### ISSUE TITLE
parallel workers issue

### ISSUE THREAD

**Issue by tinleycraig** [CMAP-REPOS/cmap_csvm#66]
@ColSmith76 Running version 0.5.4 resulted in the following error:
Running the base scenario for 2019 
Starting Firm Synthesis Step 
Processing Firm Synthesis Inputs 
Running Firm Synthesis Simulation 
Creating Base Year Establishment List 
Adding Employment Group and Spatial Variables 
Saving Firm Synthesis Database 
Starting Commercial Vehicle Touring Step 
Processing Commercial Vehicle Touring Inputs 
Loading required package: parallel
Running Commercial Vehicle Touring Simulation 
Error in value[[3L]](cond) : 
  Error in parallel workers: Error in checkForRemoteErrors(val): 4 nodes produced errors; first error: object 'StopLocType' not found
Calls: source ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
In addition: There were 17 warnings (use warnings() to see them)
Execution halted

**Comment by ColSmith76** [comment]
close this once current test run completed and results etc pushed to github
