### ISSUE TITLE
CSVM Stop Generation models: estimation

### ISSUE THREAD

**Issue by ColSmith76** [CMAP-REPOS/cmap_csvm#7]
Explore estimating the stop generation models using the local data.

**Comment by ColSmith76** [comment]
Steps:
- confirm/evaluate the sample sizes and other characteristics of the local data
- review the transferred model and identify what updates/adjustments can be estimated or asserted using the local survey data, GPS data, or other local data
- develop calibration/adjustment targets from the local data

**Comment by RickyZapata** [comment]
Below I am attaching a link to the Survey Data trips summary files:

https://resourcesystemsgroupinc-my.sharepoint.com/:f:/g/personal/ricky_zapata_rsginc_com/EkSiU7u32tNFhsFN-qZCEWcBYRQ2vuqS2fmg24Jo-r-POw?e=5YygcE

**Comment by ColSmith76** [comment]
Remaining work here is to adjust the specification of the transferred model to better match the employment categories on both the establishment and TAZ end.

**Comment by ColSmith76** [comment]
Closing this issue out, remaining work is under calibration
